nuget:
  account_feed: true
  project_feed: true
  
before_build:
  - nuget restore
  
build:
  project: ANDREICSLIB.csproj
  publish_nuget: true 
   publish_nuget_symbols: true
  include_nuget_references: true
  
after_build:
  - nuget pack ANDREICSLIB.csproj

artifacts:
  - path: '**\*.nupkg'
      
deploy:
  - provider: NuGet
    api_key: ccf3f7ea-db57-4636-aaea-3a371f63a5d8
    skip_symbols: false
  
branches:
  except:
    - /.*-osx/

configuration:
  - Release

platform:
  - x64