before_build:
  - nuget restore
  
build:
  project: ANDREICSLIB.csproj
  
after_build:
  - nuget pack ANDREICSLIB.csproj

branches:
  except:
    - /.*-osx/

configuration:
  - Release

platform:
  - x64